### ISSUE TITLE
Possible to disable in development / test modes?

### ISSUE THREAD

**Issue by adambedford** [sorry-app/devise_campaignable#11]
It'd be great to only sync with Mailchimp in Production environment!

**Comment by SirRawlins** [comment]
@adambedford this is a very nice idea Adam. At the moment I configure mine to use a separate mailing list in dev/staging/production by setting the Mailchimp details as ENV variables.

Definitely interested in disabling completely for certain environments though, how do you see it working? A config variable `config.enable_enironments =>[ :production, :staging]` or something like that?

**Comment by adambedford** [comment]
@SirRawlins I currently have a separate list for each environment too, configured by ENV variables, but it would be nice to avoid that. 

I think an `enabled_environments` config would indeed be the best approach.

I can see about putting a PR together sometime in the next week or so for this if you're interested?

**Comment by SirRawlins** [comment]
Excellent Adam. Look forward to seeing the PR should you find time
