### ISSUE TITLE
Skip campaignable if API connection causes an error

### ISSUE THREAD

**Issue by michaelti** [sorry-app/devise_campaignable#17]
After configuring devise_campaignable, when creating a new User, if there is any error with accessing the Mailchimp API (i.e. if we cannot connect to the API), then Rails throws a 500 Internal Server Error and fails to create the user.

Is there any way to just skip the Mailchimp subscription and continue creating the user if we fail to connect to Mailchimp? Our Rails app should still be functional if, for example, the Mailchimp server goes down.

**Comment by SirRawlins** [comment]
@michaelti I totally agree this would be a good idea.

The application I use this for runs DelayedJob.so the call to MailChimp is pushed into the background and doesn't risk preventing the save, which is why I've not come.accross this myself.

It shouldn't be a complicated change, we'll just rescue from MailChimp in the callback.

I'll try and take a closer.look.

**Comment by SirRawlins** [comment]
@michaelti had a quick look at the code. I think best approach would be to rescue on this method: https://github.com/sorry-app/devise_campaignable/blob/master/lib/devise_campaignable/adapters/mailchimp.rb#L8

In a similar way to we.do on the unsibscribe, swallowing and logging the error, albeit, without re-raising: https://github.com/sorry-app/devise_campaignable/blob/master/lib/devise_campaignable/adapters/mailchimp.rb#L32

Feel free to put together a PR as I likely won't get chance myself.until next week at some.poont. 🙂

**Comment by michaelti** [comment]
@SirRawlins Thanks for the quick response! This solution makes sense to me. I will try my hand at a PR – admittedly I'm a beginner with Rails so you'll want to check it over. Cheers :)

**Comment by SirRawlins** [comment]
@michaelti more than happy to review a PR for you, it's a great way to learn. :+1: welcome to the Rails community.

**Comment by SirRawlins** [comment]
@michaelti this is now available in `0.2.4` on Rubygems.

**Comment by michaelti** [comment]
@SirRawlins Thanks again!
