### ISSUE TITLE
how to disable / mock on the test environment?

### ISSUE THREAD

**Issue by jaimeiniesta** [sorry-app/devise_campaignable#6]
It would be worth thinking how this gem can be disabled / mocked on the test environment, so real calls to Mailchimp are not made when running the test suite of an app that uses it.

By now I've just skipped including the `:campaignable` module on the User on the test environment, like this, but this does not seem the cleanest solution:

``` ruby
class User < ActiveRecord::Base
  # Disable Campaignable on test environment
  if Rails.env.test?
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
           :validatable, :confirmable, :lockable, :timeoutable
  else
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
           :validatable, :confirmable, :lockable, :timeoutable, :campaignable
  end
end
```

**Comment by SirRawlins** [comment]
Hi Jaime,

This is a good point. One of the trouble with building mocking directly
into the gems codebase is that is causes bloat.

Generally whenever I'm working with anything that touches an API I put
something like the VCR gem in and it gives me a nice standard way to
control behaviour or all 3rd party APIs from one place.

Rob

**Comment by jaimeiniesta** [comment]
This is a good solution :)
