### ISSUE TITLE
Vendor Name Default 

### ISSUE THREAD

**Issue by Austex** [sorry-app/devise_campaignable#7]
Hey Guys -

Run into a problem with the :vendor_name default value. When I leave it set to the default value, I get this error:
NameError - uninitialized constant Devise::Models::Campaignable::Adapters::VendorName

When I change the default value to :mailchimp I get this error:
NameError - uninitialized constant Gibbon::API

I'm stuck at this point. I'm running Rails 4.2.4 and Ruby 2.2.1 and the latest version of Mailchimp.

Thanks!

**Comment by SirRawlins** [comment]
HI @Austex - sorry for the late reply - I've only just seen your issue.

I think we have two separate problems here. For some reason the default value isn't being used, so I'll take a look into that, for the moment use `:mailchimp`

The next issue is the dependancy on the Gibbon gem, which we use to interact with the Mailchimp API. For some reason this dependancy isn't always properly installed.

Add `gem 'gibbon'` to your gemfile just before the devise_campaignable gem.

Hopefully this will solve your issues for the moment while I patch the gem.

**Comment by Austex** [comment]
Cool. Thanks Robert! 

Reza Piri

**Comment by SirRawlins** [comment]
Taking another look at this @Austex I'm not entirely sure my initial diagnosis was correct. I actually think the gibbon gem was installed, but perhaps the wrong version.

Can you check which version of Gibbon has been installed on your environment?

**Comment by SirRawlins** [comment]
Hey @Austex - I've just cut a new version of the gem (0.1.1) which fixes the README to save the confusion over the default vendor name.

This new version also changes the dependancy definition for Gibbon, as it appears the existing one meant that Gibbon 2.x.x was being installed, which has a different API to 1.x.x - hence the error message you were getting.

Update your version of the `devise_campiaignable` gem and you shouldn't have any more problems.

**Comment by SirRawlins** [comment]
@Austex I'm going to close this issue off now as I believe it's been resolved. I've also cut another version of the gem today which upgrades to Gibbon 2.0 and uses MailChimp API v3.
